# Generated by Django 4.2.7 on 2024-01-31 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
